# Generated by Django 5.1.1 on 2024-09-06 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Brands', '0001_initial'),
        ('Types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('how_use', models.TextField(blank=True, max_length=500, null=True)),
                ('idea_price', models.FloatField(blank=True, null=True)),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='Brands.brandsmodel')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='Types.typesmodel')),
            ],
        ),
    ]
